package exception;
public class execution {
	public static void main(String[] args) {
		try {
			System.out.println(8);
		}
		catch(ArithmeticException e) {
			System.out.println("handled");
		}
		finally {
			System.out.println("sandhya");
		}
	}
}
	
		
	
	

		
	


